name: Contribution

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run build
        run: bun run build

      - name: Run lint-staged
        run: bunx lint-staged --verbose

      - name: Set status to success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const { context, github } = require('@actions/github')
            const prNumber = context.payload.pull_request.number
            const runId = context.runId
            const repo = context.repo.repo
            const owner = context.repo.owner
            const workflowUrl = `https://github.com/${owner}/${repo}/actions/runs/${runId}`
            const body = `✅ Build and lint-staged checks passed successfully! Check the [logs](${workflowUrl}) for more details.`
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: prNumber,
              body: body
            })

      - name: Set status to failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number
            const runId = context.runId
            const repo = context.repo.repo
            const owner = context.repo.owner
            const workflowUrl = `https://github.com/${owner}/${repo}/actions/runs/${runId}`
            const body = `❌ Build or lint-staged checks failed. Check the [logs](${workflowUrl}) and fix the issues.`
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: prNumber,
              body: body
            })
